export const homeObjUno = {
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Software Developer',
  headline: 'Hi, I\'m Chloe Allen',
  buttonLabel: 'Portfolio',
  imgStart: '',
  src: 'images/holder.svg',
  alt: 'obama',
  name: "Chloe Allen",
  occupation: "software developer",
  languages: "Python, Node.js, React, SQL",
  technologies: "AWS, Docker",
  education: "B.S in Information Technology",
  preference: "full stack",
}
